apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: khedmadeploy
spec:
  selector:
    app: khedma-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
