apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: khedmadeploy
  labels:
    app: khedma-backend
spec:
  type: NodePort
  selector:
    app: khedma-backend
  ports:
    - protocol: TCP
      port: 8000       # The port the service is exposed on
      targetPort: 8000 # The port on the container
      nodePort: 30001  # The port on each node
