apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-pv
  namespace: khedmadeploy
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/backend  
  

