apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: khedmadeploy
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/postgres
  storageClassName: manual

